export const skillTreeCategory = {
  id: "skillTree",
  name: "Skill Tree",
  icon: "icons/menus/Skill_Tree.webp",
  canvasHeight: 2000,
  stats: [
    {
      key: "swingHarderSkill",
      name: "Swing Harder",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Swing_Harder.webp",
      default: 0,
      x: 30,
      y: 17,
      prereqs: ["biggerBlastsSkill"],
      hasCrystals: false
    },
    {
      key: "ingotIntuitionSkill",
      name: "Ingot Intuition",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Ingot_Intuition.webp",
      default: 0,
      x: 70,
      y: 22,
      prereqs: ["oreEfficiencySkill"],
      hasCrystals: false
    },
    {
      key: "arsenalAdvancementSkill",
      name: "Arsenal Advancement",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Arsenal_Advancement.webp",
      default: 0,
      x: 35,
      y: 22,
      prereqs: ["swingHarderSkill"],
      hasCrystals: true
    },
    {
      key: "oreEfficiencySkill",
      name: "Ore Efficiency",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Ore_Efficiency.webp",
      default: 0,
      x: 70,
      y: 10,
      prereqs: ["luckyStrikesSkill"],
      hasCrystals: false
    },
    {
      key: "allRoundBomberSkill",
      name: "All-Round Bomber",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/All-Round_Bomber.webp",
      default: 0,
      x: 25,
      y: 22,
      prereqs: ["swingHarderSkill"],
      hasCrystals: true
    },
    {
      key: "biggerBlastsSkill",
      name: "Bigger Blasts",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Bigger_Blasts.webp",
      default: 0,
      x: 30,
      y: 10,
      prereqs: ["luckyStrikesSkill"],
      hasCrystals: false
    },
    {
      key: "luckyStrikesSkill",
      name: "Lucky Strikes",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Lucky_Strikes.webp",
      default: 0,
      x: 50,
      y: 5,
      prereqs: [],
      hasCrystals: false
    },
    {
      key: "waitMyCritsCanCritSkill",
      name: "Wait, My Crits Can Crit",
      type: "skill",
      layout: "card",
      states: 2,
      labels: ["Locked", "Unlocked"],
      typeImage: "icons/skill_tree/Wait_My_Crits_Can_Crit.webp",
      default: 0,
      x: 75,
      y: 22,
      prereqs: ["ingotIntuitionSkill"],
      hasCrystals: false
    },
    {
      key: "fffTest",
      name: "Test",
      type: "skill",
      layout: "card",
      states: 4,
      labels: ["Locked", "Progress 1/3", "Progress 2/3", "Maxed 3/3"],
      typeImage: "icons/skill_tree/Wait_My_Crits_Can_Crit.webp",
      default: 0,
      x: 50,
      y: 89,
      prereqs: ["waitMyCritsCanCritSkill"],
      hasCrystals: true
    }
  ]
};
